repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Chọn phiên bản mới nhất
    hooks:
      - id: trailing-whitespace  # Xóa khoảng trắng dư
      - id: end-of-file-fixer  # Đảm bảo file có newline ở cuối
      - id: check-yaml  # Kiểm tra cú pháp YAML
      - id: check-json  # Kiểm tra JSON hợp lệ
      - id: detect-aws-credentials  # Phát hiện thông tin AWS Key rò rỉ

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black  # Format code theo chuẩn PEP8

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8  # Kiểm tra lỗi style PEP8

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit  # Kiểm tra lỗi bảo mật trong code Python
        args: ["-r", "your_project_directory"]
